# Generated by Django 4.2.4 on 2023-08-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecureTransfer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
